platform :ios, '8.0'
use_frameworks!

target 'LKBVideo' do
  pod 'Masonry', '~> 1.0.1'
  pod ‘SDWebImage’, '~> 3.8.1’
  pod 'SDWebImage/WebP'
  pod 'UMengSocialCOM', '~> 5.2.1'
  pod 'MJRefresh', '~> 3.1.10'
  pod ‘FMDB’, '~> 2.6.2’
  pod 'AFNetworking', '~> 3.1.0'
end
